### ISSUE TITLE
Issue with quoted strings for map keys

### ISSUE THREAD

**Issue by slobich** [niksy/get-sass-vars#10]
Hey, great library but I have an issue when a variable contains a map with quoted strings for keys. For example this:
```scss
$colors: (
  "white": #fff,
);
```

When I run the export I get:
```
undefined:1
{"\\"white\\"":"#fff"}
     ^

SyntaxError: Unexpected token w in JSON at position 5
    at <input css z1XUS_>:1:1
    at <input css z1XUS_>:3:3
    at JSON.parse (<anonymous>)
    at file:///C:/Users/Slobich/Desktop/test/node_modules/get-sass-vars/esm/index.js:108:26
    at C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:368:16
    at C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:307:18
    at Rule.each (C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:53:16)
    at Rule.walk (C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:304:17)
    at Rule.walkDecls (C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:366:17)
    at file:///C:/Users/Slobich/Desktop/test/node_modules/get-sass-vars/esm/index.js:103:8
    at C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:392:16
    at C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:307:18 {
  postcssNode: <ref *1> Rule {
    raws: { before: '', between: ' ', semicolon: true, after: '\n' },
    type: 'rule',
    nodes: [
      Declaration {
        raws: { before: '\n  ', between: ': ' },
        type: 'decl',
        parent: [Circular *1],
        source: {
          input: Input {
            css: '.__sassVars__ {\n' +
              `  content: "$rem-size" ":" '"10px"';\n` +
              `  content: "$colors" ":" '{"\\\\"white\\\\"":"#fff"}';\n` +
              '}',
            hasBOM: false,
            id: '<input css z1XUS_>',
            [Symbol(fromOffsetCache)]: [Array]
          },
          start: { column: 3, line: 2, offset: 18 },
          end: { column: 36, line: 2, offset: 51 }
        },
        prop: 'content',
        value: `"$rem-size" ":" '"10px"'`,
        [Symbol(isClean)]: false,
        [Symbol(my)]: true
      },
      Declaration {
        raws: { before: '\n  ', between: ': ' },
        type: 'decl',
        parent: [Circular *1],
        source: {
          input: Input {
            css: '.__sassVars__ {\n' +
              `  content: "$rem-size" ":" '"10px"';\n` +
              `  content: "$colors" ":" '{"\\\\"white\\\\"":"#fff"}';\n` +
              '}',
            hasBOM: false,
            id: '<input css z1XUS_>',
            [Symbol(fromOffsetCache)]: [Array]
          },
          start: { column: 3, line: 3, offset: 55 },
          end: { column: 50, line: 3, offset: 102 }
        },
        prop: 'content',
        value: `"$colors" ":" '{"\\\\"white\\\\"":"#fff"}'`,
        [Symbol(isClean)]: false,
        [Symbol(my)]: true
      }
    ],
    parent: Root {
      raws: { semicolon: false, after: '' },
      type: 'root',
      nodes: [ [Circular *1] ],
      source: {
        input: Input {
          css: '.__sassVars__ {\n' +
            `  content: "$rem-size" ":" '"10px"';\n` +
            `  content: "$colors" ":" '{"\\\\"white\\\\"":"#fff"}';\n` +
            '}',
          hasBOM: false,
          id: '<input css z1XUS_>',
          [Symbol(fromOffsetCache)]: [ 0, 16, 53, 104 ]
        },
        start: { column: 1, line: 1, offset: 0 }
      },
      lastEach: 2,
      indexes: { '2': 0 },
      [Symbol(isClean)]: false,
      [Symbol(my)]: true
    },
    source: {
      input: Input {
        css: '.__sassVars__ {\n' +
          `  content: "$rem-size" ":" '"10px"';\n` +
          `  content: "$colors" ":" '{"\\\\"white\\\\"":"#fff"}';\n` +
          '}',
        hasBOM: false,
        id: '<input css z1XUS_>',
        [Symbol(fromOffsetCache)]: [ 0, 16, 53, 104 ]
      },
      start: { column: 1, line: 1, offset: 0 },
      end: { column: 1, line: 4, offset: 104 }
    },
    selector: '.__sassVars__',
    lastEach: 2,
    indexes: { '2': 1 },
    [Symbol(isClean)]: false,
    [Symbol(my)]: true
  }
}

Node.js v18.15.0

Slobich@DESKTOP-L72PFRS MINGW64 ~/Desktop/test
$ node export.mjs 
undefined:1
{"\\"white\\"":"#fff"}
     ^

SyntaxError: Unexpected token w in JSON at position 5
    at <input css Dhk7KQ>:1:1
    at <input css Dhk7KQ>:2:3
    at JSON.parse (<anonymous>)
    at file:///C:/Users/Slobich/Desktop/test/node_modules/get-sass-vars/esm/index.js:108:26
    at C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:368:16
    at C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:307:18
    at Rule.each (C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:53:16)
    at Rule.walk (C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:304:17)
    at Rule.walkDecls (C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:366:17)
    at file:///C:/Users/Slobich/Desktop/test/node_modules/get-sass-vars/esm/index.js:103:8
    at C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:392:16
    at C:\Users\Slobich\Desktop\test\node_modules\postcss\lib\container.js:307:18 {
  postcssNode: <ref *1> Rule {
    raws: { before: '', between: ' ', semicolon: true, after: '\n' },
    type: 'rule',
    nodes: [
      Declaration {
        raws: { before: '\n  ', between: ': ' },
        type: 'decl',
        parent: [Circular *1],
        source: {
          input: Input {
            css: '.__sassVars__ {\n' +
              `  content: "$colors" ":" '{"\\\\"white\\\\"":"#fff"}';\n` +
              '}',
            hasBOM: false,
            id: '<input css Dhk7KQ>',
            [Symbol(fromOffsetCache)]: [Array]
          },
          start: { column: 3, line: 2, offset: 18 },
          end: { column: 50, line: 2, offset: 65 }
        },
        prop: 'content',
        value: `"$colors" ":" '{"\\\\"white\\\\"":"#fff"}'`,
        [Symbol(isClean)]: false,
        [Symbol(my)]: true
      }
    ],
    parent: Root {
      raws: { semicolon: false, after: '' },
      type: 'root',
      nodes: [ [Circular *1] ],
      source: {
        input: Input {
          css: '.__sassVars__ {\n' +
            `  content: "$colors" ":" '{"\\\\"white\\\\"":"#fff"}';\n` +
            '}',
          hasBOM: false,
          id: '<input css Dhk7KQ>',
          [Symbol(fromOffsetCache)]: [ 0, 16, 67 ]
        },
        start: { column: 1, line: 1, offset: 0 }
      },
      lastEach: 2,
      indexes: { '2': 0 },
      [Symbol(isClean)]: false,
      [Symbol(my)]: true
    },
    source: {
      input: Input {
        css: `.__sassVars__ {\n  content: "$colors" ":" '{"\\\\"white\\\\"":"#fff"}';\n}`,
        hasBOM: false,
        id: '<input css Dhk7KQ>',
        [Symbol(fromOffsetCache)]: [ 0, 16, 67 ]
      },
      start: { column: 1, line: 1, offset: 0 },
      end: { column: 1, line: 3, offset: 67 }
    },
    selector: '.__sassVars__',
    lastEach: 2,
    indexes: { '2': 0 },
    [Symbol(isClean)]: false,
    [Symbol(my)]: true
  }
}

Node.js v18.15.0
```

I'm using Node.js 18.15.0. Hope you can help.

**Comment by niksy** [comment]
@slobich thanks for reporting this! This is an upstream bug in node-sass-json-functions. I’ve pushed new patch release so you should reinstall get-sass-vars and bug will be fixed.

**Comment by slobich** [comment]
@niksy Just to confirm that after I've reinstalled the package exporting a map with quoted strings for keys works. Thank you for the fix.
