### ISSUE TITLE
Not parsing scss var using `url`

### ISSUE THREAD

**Issue by samtsai** [niksy/get-sass-vars#11]
I'm having issues with parsing scss that use `url`:
https://github.com/samtsai/sass-vars-url/blob/main/index.scss

```
node sass.js
undefined:1
"url(\\"/icon.svg\\")"
        ^

SyntaxError: Unexpected non-whitespace character after JSON at position 8
    at <input css sj9M12>:1:1
    at <input css sj9M12>:2:3
    at JSON.parse (<anonymous>)
    at file:///Users/satsai/Code/sass-test/node_modules/.pnpm/get-sass-vars@4.0.0/node_modules/get-sass-vars/esm/index.js:108:26
    at /Users/satsai/Code/sass-test/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/container.js:358:16
    at /Users/satsai/Code/sass-test/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/container.js:297:18
    at Rule.each (/Users/satsai/Code/sass-test/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/container.js:53:16)
    at Rule.walk (/Users/satsai/Code/sass-test/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/container.js:294:17)
    at Rule.walkDecls (/Users/satsai/Code/sass-test/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/container.js:356:17)
    at file:///Users/satsai/Code/sass-test/node_modules/.pnpm/get-sass-vars@4.0.0/node_modules/get-sass-vars/esm/index.js:103:8
    at /Users/satsai/Code/sass-test/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/container.js:382:16
    at /Users/satsai/Code/sass-test/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/container.js:297:18 {
  postcssNode: <ref *1> Rule {
    raws: { before: '', between: ' ', semicolon: true, after: '\n' },
    type: 'rule',
    nodes: [
      Declaration {
        raws: { before: '\n  ', between: ': ' },
        type: 'decl',
        parent: [Circular *1],
        source: {
          input: Input {
            css: '.__sassVars__ {\n' +
              `  content: "$url" ":" '"url(\\\\"/icon.svg\\\\")"';\n` +
              '}',
            hasBOM: false,
            id: '<input css sj9M12>',
            [Symbol(fromOffsetCache)]: [Array]
          },
          start: { column: 3, line: 2, offset: 18 },
          end: { column: 47, line: 2, offset: 63 }
        },
        prop: 'content',
        value: `"$url" ":" '"url(\\\\"/icon.svg\\\\")"'`,
        [Symbol(isClean)]: false,
        [Symbol(my)]: true
      }
    ],
    parent: Root {
      raws: { semicolon: false, after: '' },
      type: 'root',
      nodes: [ [Circular *1] ],
      source: {
        input: Input {
          css: `.__sassVars__ {\n  content: "$url" ":" '"url(\\\\"/icon.svg\\\\")"';\n}`,
          hasBOM: false,
          id: '<input css sj9M12>',
          [Symbol(fromOffsetCache)]: [ 0, 16, 64 ]
        },
        start: { column: 1, line: 1, offset: 0 },
        end: { column: 2, line: 3, offset: 65 }
      },
      lastEach: 2,
      indexes: { '2': 0 },
      [Symbol(isClean)]: false,
      [Symbol(my)]: true
    },
    source: {
      input: Input {
        css: `.__sassVars__ {\n  content: "$url" ":" '"url(\\\\"/icon.svg\\\\")"';\n}`,
        hasBOM: false,
        id: '<input css sj9M12>',
        [Symbol(fromOffsetCache)]: [ 0, 16, 64 ]
      },
      start: { column: 1, line: 1, offset: 0 },
      end: { column: 1, line: 3, offset: 65 }
    },
    selector: '.__sassVars__',
    lastEach: 2,
    indexes: { '2': 0 },
    [Symbol(isClean)]: false,
    [Symbol(my)]: true
  }
}
```

**Comment by niksy** [comment]
Thank you for the bug report! Fixed in https://github.com/niksy/get-sass-vars/releases/tag/v4.0.1
